# Generated by Django 3.1.7 on 2023-09-30 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('promotional_code', models.CharField(max_length=20)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalMessage',
            fields=[
                ('message_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('answer', models.IntegerField(default=0)),
                ('data_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_answered', models.DateTimeField(null=True)),
                ('coupon_id', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.CASCADE, to='message_service.coupon')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='message_service.user')),
            ],
        ),
    ]
