# Generated by Django 3.1.7 on 2023-10-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_service', '0004_coupon_declined_coupon_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='declined_coupon_image_link',
            field=models.CharField(default='https://cdn.beehappyeveryday.com/images/ci/8/have-a-wonderful-day-quotes-and-images.webp', max_length=300),
        ),
    ]
