# Generated by Django 3.1.7 on 2023-10-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_service', '0006_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
